
export default {
    'Traveling': [
        'ApproachBody',
        'Docked',
        'FSDJump',
        'LeaveBody',
        'Liftoff',
        'SupercruiseEntry',
        'SupercruiseExit',
        'Touchdown',
        'Undocked',
        'ApproachSettlement',
        'USSDrop',
    ],
    'Combat': [
        'Bounty',
        'CapShipBond',
        'Died',
        'EscapeInterdiction',
        'FactionKillBond',
        'FighterDestroyed',
        'HeatDamage',
        'HullDamage',
        'Interdicted',
        'Interdiction',
        'PVPKill',
        'ShieldState',
        'ShipTargetted',
        'SRVDestroyed',
        'UnderAttack',
        'RedeemVoucher',
        'CockpitBreached',
        'SelfDestruct',
    ],
    'Exploration': [
        'DiscoveryScan',
        'Scan',
        'NavBeaconScan',
        'BuyExplorationData',
        'SellExplorationData',
        'DockSRV',
        'JetConeBoost',
        'JetConeDamage',
    ],
    'Trade': [
        'BuyTradeData',
        'MarketBuy',
        'MarketSell',
    ],
    'Mining': [
        'MiningRefined',
    ],
    'Cargo': [
        'CollectCargo',
        'EjectCargo'
    ],
    'Missions': [
        'CommunityGoalDiscard',
        'CommunityGoalJoin',
        'CommunityGoalReward',
        'MissionAbandoned',
        'MissionAccepted',
        'MissionCompleted',
        'MissionFailed',
        'MissionRedirected',
        'ScientificResearch',
        'SearchAndRescue',
        'DatalinkScan',
        'DatalinkVoucher',
        'DataScanned',
    ],
    'Engineering': [
        'MaterialCollected',
        'MaterialDiscarded',
        'MaterialDiscovered',
        'EngineerApply',
        'EngineerContribution',
        'EngineerCraft',
        'EngineerProgress',
        'MaterialTrade',
        'Synthesis',
    ],
    'Shipyard': [
        'ModuleBuy',
        'ModuleRetrieve',
        'ModuleSell',
        'ModuleSellRemote',
        'ModuleStore',
        'ModuleSwap',
        'ShipyardBuy',
        'ShipyardNew',
        'ShipyardSell',
        'ShipyardTransfer',
        'ShipyardSwap',
        'TechnologyBroker',
    ],
    'Crime': [
        'PayBounties',
        'PayFines',
        'PayLegacyFines',
        'CommitCrime',
    ],
    'MultiCrew': [
        'CrewAssign',
        'CrewFire',
        'CrewHire',
        'ChangeCrewRole',
        'CrewLaunchFighter',
        'CrewMemberJoins',
        'CrewMemberQuits',
        'CrewMemberRoleChange',
        'DockFighter',
        'EndCrewSession',
        'JoinACrew',
        'KickCrewMember',
        'LaunchFighter',
        'QuitACrew',
        'VehicleSwitch',
        'WingAdd',
        'WingInvite',
        'WingJoin',
        'WingLeave',
    ],
};
